# Dockerfile.frontend
FROM python:3.9

WORKDIR /app

COPY streamlit_app.py /app/streamlit_app.py

RUN pip install streamlit requests

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]